version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run: |
          apt -y update --fix-missing
          apt -y upgrade
          apt -y install build-essential cmake
      - checkout
      - run: |
          cmake .
          make
